name: learn-github-actions
on: 
  push:
    # branches:
    #   - main
    #   - dev
    tags:
      - '**'
  pull_request:
    branches:
      - main
      # - dev
jobs:
  check-bash-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash --version