name: learn-github-actions
on: 
# TODO: uncomment pr section and comment push.branches section before merging to main. added for dev purpose
  push:
    branches:
      - main
      - dev
    tags:
      - '**'

  # pull_request:
  #   branches:
  #     - main
  #     - dev
jobs:
  ng-build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      # - run: ls -la
      - run: npm install
      - run: npm run build:prod
      - name: Create 404 file
        run: cp docs/index.html docs/404.html
      # - run: ls -la
      - run: ls -la docs
      - name: Commit build changes to repo
        uses: EndBug/add-and-commit@v7
        with: 
          default_author: github_actions
          add: 'docs'
      # - run: 